version: '3.7'
name: soa
services:
  database_postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./first-service/src/main/resources/database/init-database-at-docker.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    networks:
      - backend-network

  first_service:
    build:
      context: first-service
      dockerfile: Dockerfile
    depends_on:
        - database_postgres
    ports:
        - '9099:9099'
    networks:
      - backend-network

  second_service:
    build:
      context: second-service
      dockerfile: Dockerfile
    ports:
      - '9100:9100'
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge